import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { Layout } from '../components/Layout';
import { Landing } from '../components/Landing';
import { useState } from 'react';

import { galleryData } from '../data';

export default function Home() {
  const [activeImage, setActiveImage] = useState(undefined);
  const [MobileNav, setMobileNav] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Lets Go!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout
        setActiveImage={setActiveImage}
        setMobileNav={setMobileNav}
      >
        {<Landing />}
      </Layout>
    </div>
  );
}
